// QUEMAR(HARD CORE) LA BD
let productos=[
    {
        nombre:"Camisa",
        fotos:["https://firebasestorage.googleapis.com/v0/b/tiendasurajpc.appspot.com/o/camisa.png?alt=media&token=16ebd96c-84ce-4ff3-865b-f8c26ad0b1fa","https://firebasestorage.googleapis.com/v0/b/tiendasurajpc.appspot.com/o/camisa1.png?alt=media&token=2d5627cf-4c35-43de-9050-e1b45f52d2d0"],
        precio:50000,
        popularidad:0,
        descripcion:" Marca: Rock Activity / Modelo	Adventure Explorer / Género	Hombre / Tipo de prenda	Remera / Diseño de la tela	Liso"
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
    {
        nombre:"",
        fotos:[],
        precio:0,
        popularidad:0,
        descripcion:""
    },
]